"""initial

Revision ID: d38971ad2038
Revises:
Create Date: 2025-11-26 13:28:24.580326

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d38971ad2038"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=128)),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("bio", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer()),
        sa.Column("minutes_to_complete", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_recipes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    op.drop_table("users")
    # ### end Alembic commands ###
